default: &default
  adapter: postgresql
  encoding: unicode
  database: learning_check_app_development
  username: postgres
  password: password
  host: db

development:
  <<: *default

test:
  <<: *default
  database: learning_check_app_test